import type { Metadata } from "next";
import "./globals.css";
import Header from "@/app/components/Header";
import Footer from "./components/Footer";
import PageTransition from "./components/PageTransition";
import { FaFacebookF, FaTiktok, FaInstagram } from "react-icons/fa";
export const metadata: Metadata = {
  title: "My Fashion Website",
  description: "Generated by Next.js + Tailwind CSS",
};
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="min-h-screen flex flex-col bg-[#fffaf8]">
        <div className="fixed top-1/3 left-6 z-50">
          <div className="bg-white/80 backdrop-blur-md rounded-2xl shadow-xl border border-gray-200 p-4 flex flex-col items-center space-y-5">
            <a
              href="https://www.tiktok.com/@millamona"
              target="_blank"
              rel="noopener noreferrer"
              className="bg-black text-white p-3 rounded-full hover:scale-110 transition-transform duration-300 shadow-md"
            >
              <FaTiktok size={20} />
            </a>

            <a
              href="https://www.facebook.com/millamona"
              target="_blank"
              rel="noopener noreferrer"
              className="bg-blue-600 text-white p-3 rounded-full hover:scale-110 transition-transform duration-300 shadow-md"
            >
              <FaFacebookF size={20} />
            </a>

            <a
              href="https://www.instagram.com/millamona"
              target="_blank"
              rel="noopener noreferrer"
              className="bg-gradient-to-tr from-yellow-400 via-pink-500 to-purple-600 text-white p-3 rounded-full hover:scale-110 transition-transform duration-300 shadow-md"
            >
              <FaInstagram size={20} />
            </a>
          </div>
        </div>
        <Header />
        <PageTransition>{children}</PageTransition>
        <Footer />
      </body>
    </html>
  );
}
